# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
steps:
- task: Application security testing@2024
  inputs:
    enableProxy: false
    enableSastScan: true
    enableSastBranching: false
    preset: 'Android'
    customPreset: 'Test'
    engineConfigId: '2'
    fullTeamName: 'CxServer'
    incScan: false
    scanTimeout: '10'
    waitingTimeBeforeRetryScan: '10'
    customfields: 'test:test'
    generatePDFReport: true
    enableDependencyScan: true
    dependencyServerURL: 'SCAServer'
    scaTeam: 'CxServer'
    projectName: 'ADORegTest'
    CheckmarxService: 'kishorsast'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
