# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NidhiJaiswal.cxsast.cx-scan-task.Application security testing@2024
  displayName: 'Application security testing'
  inputs:
    projectName: ADORegTesting
    CheckmarxService: kishorsast
    preset: All
    customPreset: Test
    engineConfigId: 1
    fullTeamName: CxServer
    fullScansScheduled: false
    projectcustomfields: 'custom1:test'
    customfields: 'test:test123'
    denyProject: true
    generatePDFReport: true
    enableDependencyScan: true
    dependencyServerURL: SCAServer
    scaTeam: CxServer

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
