# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ADOAGENT
steps:
- task: NidhiJaiswal.cxsast.cx-scan-task.Application security testing@2024
  displayName: 'Application security testing'
  inputs:
    projectName: AdoRegressionTesting
    enableSastScan: false
    enableDependencyScan: true
    dependencyServerURL: SCAServer
    scaTeam: CxServer
    isEnableScaResolver: true
    scaResolverAddParameters: '-s D:\CxProjects\ADO\VSTS-Plugin -n AdoRegressionTesting -r D:\ScaResolver\SCAResult\test.json --cxuser RahulPidde --cxpassword $(password) --cxserver https://cxprivatecloud.checkmarx.net --cxprojectname AdoRegressionTesting --sast-result-path D:\ScaResolver\SASTResult\ab.json'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
